### ISSUE TITLE
Query Parameterization

### ISSUE THREAD

**Issue by JherezTaylor** [servsecCrucible/pixeltrack#13]
Can't figure out how to get this to return an object. 

 When I do `x = Campaign[id]` it returns an object of type `Campaign`. However, when I setup a query param like:
`x = Campaign.where(id: :$find_id)`  
`z = x.call(:select, :find_id => id)`

z comes back as an array.

**Comment by JherezTaylor** [comment]
Doesn't look like the prepared statements can return the results as a model.

http://sequel.jeremyevans.net/rdoc/files/doc/object_model_rdoc.html
http://sequel.jeremyevans.net/rdoc/files/doc/prepared_statements_rdoc.html
http://ricostacruz.com/cheatsheets/sequel.html
https://github.com/jeremyevans/sequel

**Comment by rjollet** [comment]
But what is the issue ? Where return an array because it is a filter

**Comment by JherezTaylor** [comment]
How the tests are written, it creates a test model and compares the result from the route with that model. I just created an issue for it so I can make notes on it, but it's not a problem.

**Comment by JherezTaylor** [comment]
Offending Route: https://github.com/servsecCrucible/pixeltrack/blob/master/app.rb#L57
Corresponding Test: https://github.com/servsecCrucible/pixeltrack/blob/master/specs/campaign_spec.rb#L31

@soumyaray

**Comment by JherezTaylor** [comment]
@soumyaray

**Comment by soumyaray** [comment]
Still looking into this.  When I try it on my project:

```
ds = Project.where(name: :$n)
result = ds.call(:select, :n => 'Soumya Project').first
result.class
# => Project
```

So its working for me. Have to see why its different for you.

**Comment by JherezTaylor** [comment]
On your configshare repo? The branches that are there. I'll have to double check because even a prepared statement as an insert was failing the test as well.

**Comment by soumyaray** [comment]
Hi, I've made a special branch of ConfigShareAPI for you (https://github.com/ISS-Security/configshare/tree/3-secure_accounts-jherez), with a populated db/dev.db included.  Please open it up in tux and see if my above code works?

**Comment by JherezTaylor** [comment]
Yea, it works in Tux. Try this from within the route then run the tests. This is the body of controllers/projects_controller.rb. 

``` ruby
    id = params[:id]
    ds = Project.where(name: :$n)
    project = ds.call(:select, :n => id).first
    configurations = project ? Project[id].configurations : []

    if project
      JSON.pretty_generate(data: project, relationships: configurations)
    else
      halt 404, "PROJECT NOT FOUND: #{id}"
    end
```

Edit, did something foolish.

**Comment by JherezTaylor** [comment]
Stack trace 
[output.txt](https://github.com/servsecCrucible/pixeltrack/files/231325/output.txt)

**Comment by JherezTaylor** [comment]
Yea I'm a fool, I noticed what it was now, unchanged variable names in the where clause. I was pretty sure I accounted for that on our own project but if it's working here then it means that I must not have done that. The correct verison follows below.

``` ruby
    id = params[:id]
    ds = Project.where(id: :$n)
    project = ds.call(:select, :n => id).first
    configurations = project ? project.configurations : []

    if project
      JSON.pretty_generate(data: project, relationships: configurations)
    else
      halt 404, "PROJECT NOT FOUND: #{id}"
    end
```

**Comment by soumyaray** [comment]
ok - glad this worked out!
