### ISSUE TITLE
[Threat: Integrity] ID random generator uses time as a key

### ISSUE THREAD

**Issue by rjollet** [servsecCrucible/pixeltrack#3]
If two users register at the exact same time there will be a conflict

**Comment by JherezTaylor** [comment]
Vulnerability: random key generator produces same keys within given second
Vector: send multiple `POST /resource` requests within same second

**Comment by JherezTaylor** [comment]
Fixed with update to models.

**Comment by soumyaray** [comment]
why was this issue reopened?

**Comment by JherezTaylor** [comment]
Oh, for the tables that still have a sequential primary key, don't they face the same problem?

**Comment by soumyaray** [comment]
sorry i didn't see your earlier comment -- no, the database is tasked with incrementing primary keys and it will block on creation.

**Comment by JherezTaylor** [comment]
Ah. Alright
