### ISSUE TITLE
Error when creating campaign

### ISSUE THREAD

**Issue by JherezTaylor** [servsecCrucible/pixeltrack#35]
I don't know if it's server or client side yet, will investigate.

**Comment by JherezTaylor** [comment]
@rjollet- are you getting `Invalid HTTP format, parsing fails` when running the app view locally?

**Comment by rjollet** [comment]
yes I don't know why

**Comment by rjollet** [comment]
But I think it is just a warning because it works

**Comment by JherezTaylor** [comment]
Ah, that's why you deploy so often? Okay I'll work around it.

**Comment by JherezTaylor** [comment]
It straight up fails to login for me.

**Comment by rjollet** [comment]
Strange because I can login locally

**Comment by JherezTaylor** [comment]
In `security.rb` in the `config.csp`, set upgrade_insecure _requests to false
